### ISSUE TITLE
rules 可以从DB加载吗？

### ISSUE THREAD

**Issue by ttxs0109** [rongfengliang/easy-rules-spring-boot-starer#1]
rule从db加载，便于业务对rule的修改和增加,删除

**Comment by rongfengliang** [comment]
@yiyuan0109 好的后期添加，我是计划添加直接基于配置中心工具的，不太希望直接使用db

**Comment by rongfengliang** [comment]
@yiyuan0109 

 https://github.com/rongfengliang/easy-rules-centraldogma-spring-boot-starter 可以试试这个，目前基于centraldogma进行规则管理，可以实现实时更新，同时规则也可以利用centraldogma 镜像git 的能力，直接基于git 管理规则
